// Regenerates src/sound/clips.ts from sounds/*.ogg — the single source of truth for move sounds.
import { existsSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { basename } from 'node:path';

const soundsDir = new URL('../sounds/', import.meta.url);
const outFile = new URL('../src/sound/clips.ts', import.meta.url);

if (!existsSync(soundsDir)) {
  throw new Error('build-clips: sounds/ directory not found');
}

const oggFiles = readdirSync(soundsDir)
  .filter((name) => name.endsWith('.ogg'))
  .sort();

if (oggFiles.length === 0) {
  throw new Error('build-clips: no .ogg files found in sounds/');
}

const entries = oggFiles.map((name) => {
  const id = basename(name, '.ogg');
  const base64 = readFileSync(new URL(name, soundsDir)).toString('base64');
  // Quoted: a stem such as "capture-x" is not a valid bare object key.
  return `  '${id}': 'data:audio/ogg;base64,${base64}',`;
});

const output = [
  '// Generated by scripts/build-clips.mjs from sounds/*.ogg. Do not edit; run `npm run build:clips`.',
  'export const CLIPS: Record<string, string> = {',
  ...entries,
  '};',
  '',
].join('\n');

writeFileSync(outFile, output);
